### ISSUE TITLE
Swarth + uBlock Origin causes entire page to be black while picking elements for a custom filter

### ISSUE THREAD

**Issue by NintendoManiac64** [FranklinDM/Swarth#10]
Occurs with "stylesheet processor" and "simple stylesheet".

Interestingly, using "color inversion" results in a different issue - the text box instead appears in the bottom right corner of the page itself rather than in your browser (meaning you have to scroll to the bottom of web page first).

![screenshot](https://user-images.githubusercontent.com/11896003/212419802-79161fe8-bbb7-41ab-95c1-c40f68b10fb2.png)

**Comment by fofajardo** [comment]
Confirmed. This should be relatively straightforward and will involve excluding/tweaking the overlay that uBO injects to the page.

**Comment by NintendoManiac64** [comment]
Should I make a separate issue for the thing I described regarding "color inversion"?

**Comment by fofajardo** [comment]
@NintendoManiac64 can you test if this is still a problem on v1.0.8 with both Stylesheet Processor and Simple Stylesheet modes? Thanks!

As for color inversion, there isn't anything I can do about it as this is inherently a problem with how uBlock Origin's element picker inserts its overlay. Rather than being isolated from the page (e.g. as part of the browser UI), it inserts the element picker as an `iframe` on the actual page itself, and because of that, it is affected by layout quirks resulting from using `invert` on the document element.

Here's a testcase where the box appears on the corner even without Swarth enabled (what's odd is this is only rendered black on UXP-based applications):
[invert.zip](https://github.com/FranklinDM/Swarth/files/10516429/invert.zip)

**Comment by NintendoManiac64** [comment]
Seems like it's working in v1.0.8
